# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update Site

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Cache Maven packages
      uses: actions/cache@v3
      # On deployment do not use a cache
      if: github.event_name != 'push'
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -U -B package --file pom.xml

    - name: Deploy GH Pages
      # Deploy on pushes to main
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        BRANCH: gh-pages 
        FOLDER: target/repository
        CLEAN: true 
   
